### ISSUE TITLE
UPDATE Support

### ISSUE THREAD

**Issue by jordiyeh** [LocusEnergy/sqlalchemy-vertica-python#30]
Following the Object Relational Tutorial https://docs.sqlalchemy.org/en/rel_1_2/orm/tutorial.html

There seems to be an issue with the UPDATE statement return row count. The update SQL syntax is correct.

>>> ed_user.password = 'asdf'
>>> session.dirty
IdentitySet([<User(name='ed', fullname='Ed Jones', password='asdf')>])
>>> session.commit()
2019-01-02 12:14:05,058 INFO sqlalchemy.engine.base.Engine UPDATE "user" SET password=:password WHERE "user".id = :user_id
2019-01-02 12:14:05,058 INFO sqlalchemy.engine.base.Engine {'password': 'asdf', 'user_id': 500001}
2019-01-02 12:14:05,123 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/pyvirtualenv/rest_test/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 797, in _emit_update_statements
    (table.description, len(records), rows))
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'user' expected to update 1 row(s); -1 were matched.

I am trying to figure out how to fix and I would appreciate any guidance.

The following is working great.
Querying
Rollback
Common Filter Operators
Returning Lists and Scalars
Using Textual SQL
Counting
Deleting

**Comment by lemeryfertitta** [comment]
I would venture a guess that this is related: https://github.com/vertica/vertica-python#rowcount-oddities

It may be that there is a workaround we could implement inside this library, but it also might be something that the connector is responsible for reporting correctly. If you find a workaround that you think fits here, feel free to submit a patch and I will be happy to review and release. Thanks!

**Comment by jordiyeh** [comment]
The following pull requests allowed me to use the UPDATE without errors

https://github.com/LocusEnergy/sqlalchemy-vertica-python/pull/31

Thanks for pointing the rowcount oddity with vertica-python

**Comment by lemeryfertitta** [comment]
Thanks @jordiyeh! Fix released in `0.4.3`
