### ISSUE TITLE
Issues connecting to vertica

### ISSUE THREAD

**Issue by hc000** [LocusEnergy/sqlalchemy-vertica-python#9]
I'm trying to use this with sql alchemy to connect to vertica.

However i'm getting errors.

``` 
sa.create_engine('vertica+vertica_python://user:pass@ip:port/name').connect()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1122, in _do_get
    return self._pool.get(wait, self._timeout)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/queue.py", line 145, in get
    raise Empty
sqlalchemy.util.queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 166, in write
    for data in message.fetch_message():
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/messages/message.py", line 84, in fetch_message
    yield self.get_message()
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/messages/message.py", line 80, in get_message
    bytes_ = self.read_bytes()
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/messages/frontend_messages/password.py", line 60, in read_bytes
    encoded_pw = self.encoded_password()
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/messages/frontend_messages/password.py", line 57, in encoded_password
    raise ValueError("unsupported authentication method: {0}".format(self._auth_method))
ValueError: unsupported authentication method: 11

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 25, in connect
    return Connection(kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 45, in __init__
    self.startup_connection()
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 271, in startup_connection
    'salt': getattr(message, 'salt', None)}))
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 180, in write
    raise_from(errors.ConnectionError, e)
  File "<string>", line 2, in raise_from
vertica_python.errors.ConnectionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 25, in connect
    return Connection(kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 45, in __init__
    self.startup_connection()
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 271, in startup_connection
    'salt': getattr(message, 'salt', None)}))
  File "/usr/local/lib/python3.5/dist-packages/vertica_python/vertica/connection.py", line 180, in write
    raise_from(errors.ConnectionError, e)
  File "<string>", line 2, in raise_from
sqlalchemy.exc.DatabaseError: (vertica_python.errors.ConnectionError)```

**Comment by lemeryfertitta** [comment]
@hc000 I believe your issue is not related to this repository, but is instead an issue with the underlying vertica_python connector. This looks very similar to [this issue](https://github.com/uber/vertica-python/issues/180) from that repository.
